In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Mobile phone price.csv')
df.columns

Index(['Brand', 'Model', 'Storage', 'RAM', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)', 'Price ($)'],
      dtype='object')

In [3]:
for i in range(len(df['Price ($)'])):
    a=""
    s=df['Price ($)'][i]
    for j in range(len(s)):
        if(s[j]!='$' and s[j]!=','):
            a=a+s[j]
        elif(s[j]==' '):
            break
    df['Price ($)'][i]=a
df['Price ($)']

C:\Users\rajse\AppData\Local\Temp\ipykernel_28096\3643351153.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price ($)'][i]=a

0       999
1      1199
2       899
3       279
4       799
       ...
402    1049
403     349
404    1099
405     429
406     649
Name: Price ($), Length: 407, dtype: object

In [4]:
df['Price ($)']= df['Price ($)'].astype('int64')
df['Price ($)'].dtype

dtype('int64')

In [5]:
len(df['Model'][0])

13

In [6]:
X= df.iloc[:,0:7]

X['Brand'] = pd.factorize(X['Brand'])[0]
X['Model'] = pd.factorize(X['Model'])[0]

In [7]:
print(X.columns)

Index(['Brand', 'Model', 'Storage', 'RAM', 'Screen Size (inches)',
       'Camera (MP)', 'Battery Capacity (mAh)'],
      dtype='object')

In [8]:
X['Storage'] = X['Storage'].str.replace('GB', '')
X['Storage'] = X['Storage'].astype('int64')
X['RAM'] = X['RAM'].str.replace('GB', '')
X['RAM'] = X['RAM'].astype('int64')

In [9]:
print(X['Storage'].dtype)
print(X['RAM'].dtype)

int64
int64

In [10]:
X

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh)
0,0,0,128,6,6.1,12 + 12 + 12,3095
1,1,1,256,12,6.8,108 + 10 + 10 + 12,5000
2,2,2,128,8,6.7,48 + 50 + 8 + 2,4500
3,3,3,128,6,6.67,64 + 8 + 5 + 2,5020
4,4,4,128,8,6.4,50 + 12.2,4614
...,...,...,...,...,...,...,...
402,1,222,128,8,6.7,12+64+12,4300
403,3,236,128,6,6.57,48+8+2+2,4160
404,0,237,128,6,6.7,12+12+12,3687
405,5,238,128,8,6.4,48+13+8+2,4025
406,1,199,128,6,6.7,48+12+5,4500

In [11]:
X.head(50)

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh)
0,0,0,128,6,6.1,12 + 12 + 12,3095
1,1,1,256,12,6.8,108 + 10 + 10 + 12,5000
2,2,2,128,8,6.7,48 + 50 + 8 + 2,4500
3,3,3,128,6,6.67,64 + 8 + 5 + 2,5020
4,4,4,128,8,6.4,50 + 12.2,4614
5,0,5,128,4,6.1,12 + 12,2815
6,1,6,256,8,6.7,12 + 12,3300
7,3,7,128,6,6.67,48 + 8 + 2 + 2,5160
8,5,8,128,8,6.55,50 + 13 + 16 + 2,4500
9,6,9,256,12,6.78,50 + 48 + 12 + 8,4500
10,2,10,128,6,6.43,64 + 8 + 2,4500
11,1,11,128,6,6.5,64 + 12 + 5 + 5,4500
12,7,12,128,8,6.62,64 + 8 + 2,5000
13,0,13,64,4,5.4,12 + 12,2227
14,5,14,256,12,6.7,50 + 50 + 13 + 3,4500
15,3,15,128,6,6.55,64 + 8 + 5,4250
16,1,16,128,8,6.2,64 + 12 + 12,4000
17,6,17,128,6,6.51,50 + 2 + 2,5000
18,7,18,128,6,6.5,48 + 2 + 2,5000
19,5,19,128,8,6.43,48 + 8 + 2 + 2,4310
20,3,20,128,6,6.5,50 + 8 + 2 + 2,6000
21,1,21,128,4,6.6,48 + 5,5000
22,7,22,128,6,6.5,48 + 50 + 2,5000
23,2,23,128,8,6.55,48 + 50 + 2,4500
24,3,24,128,6,6.67,108 + 8 + 5 + 2,5020
25,0,25,64,4,6.1,12 + 12,3110
26,1,26,32,3,6.5,13 + 2 + 2,5000
27,5,27,128,6,6.5,48 + 2 + 2,5000
28,6,28,32,3,6.51,13 + 2,5000
29,7,29,128,4,6.5,50 + 2 + 2,6000
30,1,30,128,6,6.7,64 + 12 + 5 + 5,5000
31,3,31,128,4,6.5,50 + 8 + 2 + 2,5000
32,0,32,64,3,4.7,12,1821
33,5,33,128,6,6.5,13 + 2 + 2,5000
34,6,34,128,8,6.58,50 + 2 + 2,5000
35,7,35,128,4,6.5,13 + 2 + 2,6000
36,1,36,128,6,6.4,48 + 5 + 2,5000
37,2,37,128,8,6.43,50 + 8 + 2,4500
38,3,38,64,4,6.5,48 + 2 + 2,5000
39,0,39,64,3,6.1,12,2942
40,5,40,64,3,6.52,13 + 2 + 2,5000
41,7,41,64,4,6.5,13 + 2 + 2,5000
42,1,42,64,4,6.4,48 + 8 + 2 + 2,6000
43,5,43,128,8,6.43,64 + 8 + 2 + 2,4310
44,3,44,128,8,6.67,48 + 8 + 5,4520
45,0,13,64,4,5.4,12 + 12,2227
46,6,45,128,8,6.44,64 + 8,4000
47,7,46,128,4,6.5,48 + 2 + 2,5000
48,1,47,64,4,6.5,48 + 5 + 2 + 2,6000
49,5,48,64,4,6.52,13 + 2 + 2,5000

In [12]:
for i in range(len(X['Screen Size (inches)'])):
    a=""
    s=X['Screen Size (inches)'][i]
    for j in range(len(s)):
        if(s[j]!=' '):
            a=a+s[j]
        else:
            break
    X['Screen Size (inches)'][i]=a
X['Screen Size (inches)']

C:\Users\rajse\AppData\Local\Temp\ipykernel_28096\2592431841.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Screen Size (inches)'][i]=a

0       6.1
1       6.8
2       6.7
3      6.67
4       6.4
       ...
402     6.7
403    6.57
404     6.7
405     6.4
406     6.7
Name: Screen Size (inches), Length: 407, dtype: object

In [13]:
X['Screen Size (inches)']=X['Screen Size (inches)'].astype(float)
print(X['Screen Size (inches)'].dtype)

float64

In [14]:
for i in range(len(X['Camera (MP)'])):
    a=""
    s=X['Camera (MP)'][i]
    for j in range(len(s)):
        if(s[j]!='+' and s[j]!='M'):
            a=a+s[j]
        else:
            break
    X['Camera (MP)'][i]=a
X['Camera (MP)']

C:\Users\rajse\AppData\Local\Temp\ipykernel_28096\69336157.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Camera (MP)'][i]=a

0       12
1      108
2       48
3       64
4       50
       ...
402      12
403      48
404      12
405      48
406      48
Name: Camera (MP), Length: 407, dtype: object

In [15]:
X

,Brand,Model,Storage,RAM,Screen Size (inches),Camera (MP),Battery Capacity (mAh)
0,0,0,128,6,6.10,12,3095
1,1,1,256,12,6.80,108,5000
2,2,2,128,8,6.70,48,4500
3,3,3,128,6,6.67,64,5020
4,4,4,128,8,6.40,50,4614
...,...,...,...,...,...,...,...
402,1,222,128,8,6.70,12,4300
403,3,236,128,6,6.57,48,4160
404,0,237,128,6,6.70,12,3687
405,5,238,128,8,6.40,48,4025
406,1,199,128,6,6.70,48,4500

In [16]:
X['Camera (MP)']=X['Camera (MP)'].astype(float)

In [17]:
print(X['Screen Size (inches)'].dtype)

float64

In [18]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Brand                   407 non-null    int64
 1   Model                   407 non-null    int64
 2   Storage                 407 non-null    int64
 3   RAM                     407 non-null    int64
 4   Screen Size (inches)    407 non-null    float64
 5   Camera (MP)             407 non-null    float64
 6   Battery Capacity (mAh)  407 non-null    int64
dtypes: float64(2), int64(5)
memory usage: 22.4 KB

In [19]:
Y=df.iloc[:,-1]
Y.dtype

dtype('int64')

In [20]:
Y[272]

249

In [21]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(X, Y, test_size= 0.25, random_state=0)  
  
# feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

In [22]:
from sklearn.tree import DecisionTreeRegressor 
  
regressor = DecisionTreeRegressor(random_state = 0) 
  
regressor.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

In [23]:
y_pred_list = []

for row in x_test:
    
    row = row.reshape(1, -1)
    
    y_pred = regressor.predict(row)
    print(y_pred)
    
    y_pred_list.append(y_pred[0])


y_pred_array = np.array(y_pred_list)

[99.]
[199.]
[549.]
[265.66666667]
[184.]
[699.]
[329.]
[141.5]
[164.]
[799.]
[1199.]
[139.]
[1099.]
[449.]
[384.]
[149.]
[449.]
[249.]
[349.]
[299.]
[179.]
[199.]
[699.]
[299.]
[279.]
[219.]
[549.]
[499.]
[384.]
[399.]
[149.]
[1199.]
[249.]
[749.]
[399.]
[149.]
[449.]
[399.]
[279.]
[455.66666667]
[149.]
[399.]
[329.]
[249.]
[1099.]
[1199.]
[799.]
[279.]
[429.]
[244.]
[199.]
[349.]
[329.]
[1049.]
[399.]
[399.]
[162.33333333]
[599.]
[1099.]
[199.]
[399.]
[139.]
[699.]
[799.]
[349.]
[699.]
[449.]
[329.]
[202.33333333]
[239.]
[799.]
[219.]
[649.]
[449.]
[259.]
[269.]
[532.33333333]
[209.]
[129.]
[699.]
[532.33333333]
[299.]
[239.]
[164.]
[699.]
[199.]
[249.]
[349.]
[265.66666667]
[159.]
[199.]
[189.]
[169.]
[279.]
[249.]
[799.]
[199.]
[314.]
[199.]
[499.]
[299.]
[299.]

In [24]:
x_test.shape

(102, 7)

In [25]:
type(y_pred_array)
print(y_pred_array.ndim)

1

In [26]:
type(y_test)

pandas.core.series.Series

In [27]:
y_test=np.array(y_test)
type(y_test)
print(y_test)

[  99  179  659  289  199  499  329  139  149  999  999  149  999  399
  329  149  449  219  399  399  219  229  599  299  199  279  549  499
  329  349  149 1399  199  599  399  139  449  399  229  459  149  249
  279  179  999 1199  749  199  429  229  189  329  699 1399  229  699
  149  299 1099  169  329  139  699  799  399  799  599  329  179  249
  799  219  649  319  249  249  499  179  139 1199  599  319  219  159
  799  239  239  499  279  179  229  199  119  279  329  799  269  309
  199  699  329  249]

In [28]:
from sklearn.metrics import mean_absolute_error, r2_score


mae = mean_absolute_error(y_test, y_pred_array)

r2 = r2_score(y_test, y_pred_array)

accuracy = (1 - mae / y_test.mean()) * 100

print("Accuracy: {:.2f}%".format(accuracy))
print("R-squared score: {:.4f}".format(r2))

Accuracy: 85.30%
R-squared score: 0.8665

In [29]:
def suggest_features():
    price_range = input('Enter the price range you are looking for: ')
    price_range = float(price_range)
    
    
    features = [0]*7 
    max_price = price_range
    max_iterations = 100
    iterations = 0
    while regressor.predict([features])[0] <= max_price and iterations < max_iterations:
        max_price += 10
        features[0] = max_price
        iterations += 1
    max_price -= 10
    features[0] = max_price
    filtered_data = df[df['Price ($)'] <= price_range]
    
    suggested_phone = filtered_data.loc[filtered_data['Price ($)'].idxmax()]
    
    
    print('For a price range of', price_range, 'you can get a phone with the following features:')
    for feature, value in suggested_phone.items():
        if feature != 'Price ($)':
            print(feature + ':', value)

            
def predict_mobile_price():
    brand=input('Enter the brand name')
    model=input('Enter the model name')
    stor=int(input('Enter the storage(in GB)'))
    ram = int(input('Enter RAM (in GB): '))
    screen = float(input('Enter screen size(in inches): '))
    pc = float(input('Enter primary camera resolution (in MP): '))
    battery= int(input('Enter battery power (in mAh): '))
    new_features = pd.DataFrame({
        'Brand': ['brand'],
        'Model': ['model'],
        'Storage': [stor],
        'RAM': [ram],
        'Screen Size (inches)': [screen],
        'Camera (MP)': [pc],
        'Battery Capacity (mAh)': [battery],
    })


    new_features['Brand'] = pd.factorize(new_features['Brand'], sort=True)[0]
    new_features['Model'] = pd.factorize(new_features['Model'], sort=True)[0]

    
    new_features = pd.DataFrame(st_x.transform(new_features), columns=new_features.columns)

    
    price= regressor.predict(new_features)[0]
    print("The predicted price is: $", round(price, 2))
    
    
choice=int(input("Enter 1 if you want to predict the price of the mobile by providing us features or  Enter 2 if you want to get the features in the price range provided by you "))

if choice==1:
    predict_mobile_price()
        
elif choice==2:
    suggest_features()
else:
    print("please choose correct number")

Enter 1 if you want to predict the price of the mobile by providing us features or  Enter 2 if you want to get the features in the price range provided by you 2
Enter the price range you are looking for: 1200
For a price range of 1200.0 you can get a phone with the following features:
Brand: Samsung
Model: Galaxy S21 Ultra
Storage: 256 GB
RAM: 12 GB
Screen Size (inches): 6.8
Camera (MP): 108 + 10 + 10 + 12
Battery Capacity (mAh): 5000